# Generated by Django 5.1.4 on 2025-01-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_alter_diario_pessoas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='pessoas',
            field=models.ManyToManyField(to='diario.pessoa'),
        ),
    ]
